### PR TITLE
add eth_coinbase

### PR DESCRIPTION
**Pull request by estebanmino**
Fixes BX-1266
Figma link (if any):

## What changed (plus any additional context for devs)

adding eth_coinbase provider method

## Screen recordings / screenshots

https://www.loom.com/share/ce4cd5f514544ad3bfacd02c6e22e9f7

### CODE REVIEW

**Review by brunobar79 — COMMENTED** [review]
I tested both methods on MM and I think they don't behave exactly the same.
`eth_coinbase` returns the address directly while `eth_accounts` returns an array with the address inside.

See

Screen Shot 2024-01-24 at 12 13 59 PM

**Comment by estebanmino** [comment]
> I tested both methods on MM and I think they don't behave exactly the same. `eth_coinbase` returns the address directly while `eth_accounts` returns an array with the address inside.
> 
> See
> 
> Screen Shot 2024-01-24 at 12 13 59 PM

oh yeah that's right https://ethereum.org/en/developers/docs/apis/json-rpc#eth_coinbase

**Comment by estebanmino** [comment]
ok ready @brunobar79

**Review by DanielSinclair — APPROVED** [review]
Working for me 👌 
300981274-c1ce8781-b08c-4f0f-bece-3667c7d71696

**Review by brunobar79 — APPROVED** [review]

**Pull request merged**
