### PR TITLE
chore: update swaps sdk & rip out WRAPPED_ASSET dependency

### PR DESCRIPTION
**Pull request by welps**
This removes the dependency on hardcoded addresses for wrapped native assets

### CODE REVIEW

**Comment by DanielSinclair** [comment]
@BrodyHughes Can you do a QA pass on this? Thank you!

**Review by BrodyHughes — APPROVED** [review]
Checked:
- Swaps: ✅
    - Mainnet swap: ✅
    - OP swap: ✅
    - Arb swap: ✅
    - Degen swap: ✅
    - Ape swap: ✅
- Wraps: ✅
    - Mainnet wrap / unwrap: ✅
    - OP wrap / unwrap: ✅
    - Arb wrap / unwrap: ✅
    - Degen wrap / unwrap: ✅
    - Ape wrap / unwrap: ✅
        - not a regression, but flagged an issue with balance of wape not showing up and with wraps being labelled as ‘deposit’ instead of ‘wraps

**Comment by welps** [comment]
@BrodyHughes Can you confirm if the e2e swap failure is from my branch or if it 's widespread? if the latter, can we just merge this?

**Comment by BrodyHughes** [comment]
> @BrodyHughes Can you confirm if the e2e swap failure is from my branch or if it 's widespread? if the latter, can we just merge this?

I just reran the test and it passed. Still need another review though before merging.

**Pull request merged**
