### PR TITLE
e2e: shortcut onboarding helper

### PR DESCRIPTION
**Pull request by BrodyHughes**
adds a helper for onboarding using all shortcuts / keyboard nav. will use this in the shortcut tests.

### CODE REVIEW

**Review by estebanmino — COMMENTED** [review]
are we using this somewhere?

**Comment by BrodyHughes** [comment]
> are we using this somewhere? 

nope! but i'm going to in the next tests i'm writing. just was trying to keep the PRs smaller / simpler.

**Comment by estebanmino** [comment]
> > are we using this somewhere?
> 
> @estebanmino nope! but i'm going to in the next tests i'm writing. just was trying to keep the PRs smaller / simpler.

wdyt to mrge this when the first test you use this with? imo we shouldn't merge code we're not using

**Comment by BrodyHughes** [comment]
adding this to the new test i wrote

**Pull request closed without merging**
