### PR TITLE
limit percentage reduction in token details

### PR DESCRIPTION
**Pull request by magiziz**
Fixes BX-1564
Figma link (if any):

## What changed (plus any additional context for devs)

Capped the percentage on the token details page to not decrease more than `-100%`.

## Screen recordings / screenshots

**Before:**

BX-1564 (after)

**After:**

BX-1564 (before)

## What to test

Select a token that experienced a significant decrease over time such as $DEGEN and make sure that when hovering over the graph at its lowest point the decrease does not exceed -100%.

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
i'm gonna approve but this seems like a bigger issue? not sure if from BE or if we calculate this number

**Comment by magiziz** [comment]
@estebanmino Yeah could be. I looked at our percentage logic [here](https://github.com/rainbow-me/browser-extension/blob/master/src/entries/popup/pages/home/TokenDetails/PriceChart.tsx#L248-L249) and the calculation is done correctly. I think $DEGEN token just had a significant drop.

**Review by greg-schrammel — CHANGES_REQUESTED** [review]
pretty sure the `percentDiff` fn is wrong, we should fix that instead, price -100% and no being 0, is just wrong

**Comment by magiziz** [comment]
We've found out that that there is a small bug in the charts where it shows `Infinity`. I've messaged the backend team to let them know.

**Comment by DanielSinclair** [comment]
Moved to draft while we workout the Backend change

**Comment by DanielSinclair** [comment]
Closing for now because I assume Backend will handle this fix

**Review by greg-schrammel — APPROVED** [review]

**Pull request merged**
