### PR TITLE
[BX-1219] Hide NFTs

### PR DESCRIPTION
**Pull request by derHowie**
## What changed (plus any additional context for devs)
We have added the ability to hide NFTs from the context menu or the ... dropdown within NFT details. Hidden Nfts will appear in a 'hidden' collection placed at the bottom of the Nfts collection list. Nfts can be unhidden within the same menus.

## Screen recordings / screenshots
PoW: https://recordit.co/pEghkv1snb

## What to test
Hide some NFTs, make sure they are filtered out of the main lists, but do appear in the 'Hidden' collection. Try using the toggle to unhide NFTs. Make sure this behavior works across wallet addresses.

### CODE REVIEW

**Review by estebanmino — COMMENTED** [review]
i'm seeing this

image


seems to be hiding correctly, any option to unhide?

**Comment by derHowie** [comment]
> i'm seeing this
> 
> image
> seems to be hiding correctly, any option to unhide?

Oh weird, I dunno why the diff in the lang file didn't get committed. I just pushed it up. 

Yeah, you can unhide by setting the NFT display option to collections view and scrolling to the bottom to view the 'Hidden' collection. You'll also see this 'unhide' option in the details view if you navigate there from the hidden collection.

Screen Shot 2024-01-02 at 12 30 42 PM

**Review by greg-schrammel — APPROVED** [review]
how about a custom icon for the hidden collection?

**Review by DanielSinclair — APPROVED** [review]
Functionality looks good to me!

**Pull request merged**
