### PR TITLE
fix: `Cmd+K` not working after using token shortcuts (hide / pin)

### PR DESCRIPTION
**Pull request by magiziz**
Fixes BX-1376
Figma link (if any):

## Screen recordings / screenshots

https://github.com/rainbow-me/browser-extension/assets/53529533/e093418e-61b0-40c7-90ba-b3dd8a2d9642

## What to test
- `Cmd+K` should work right after interacting with the token shortcuts in the context menu. E.g `H` for hide and `P` for pin.

### CODE REVIEW

**Review by DanielSinclair — CHANGES_REQUESTED** [review]
@magiziz Didn't seem to resolve the issue for me. I see the toast, and the shortcuts remains blocked until the next navigation event

**Comment by nickbytes** [comment]
This has been open for a couple weeks, what do we need to do to get this across the line @magiziz ?

**Review by DanielSinclair — APPROVED** [review]
Looks good to me!

**Comment by magiziz** [comment]
@DanielSinclair I went ahead and added the fix to this PR https://github.com/rainbow-me/browser-extension/pull/1425. There are a lot of fixed included in that PR so went ahead and added it there. We can close this one.

**Pull request closed without merging**
