### PR TITLE
fix: add zora again if is missing

### PR DESCRIPTION
**Pull request by estebanmino**
Fixes BX-1420
Figma link (if any):

## What changed (plus any additional context for devs)

adding zora back to the state if is missing for these users

details and POW  video in ticket

### CODE REVIEW

**Review by greg-schrammel — COMMENTED** [review]
this has the same issue I tried to solve with this https://github.com/rainbow-me/browser-extension/pull/1470

if the last time the user opened the bx this store was at version 2, the only migration that's happening is the one adding support for blast

I think we can fix this by using 
```diff
- if (version === 4)
+ if (version <= 4)
```
or merging that util

**Comment by estebanmino** [comment]
@greg-schrammel i'm down to merfge that, is already approved

**Review by DanielSinclair — APPROVED** [review]
Tested from the previous release (with existing Zora RPC) and worked for that

**Review by BrodyHughes — APPROVED** [review]
got my app into a broken state (Zora RPC gone) and this fixed it! nice work.

<video src="https://github.com/rainbow-me/browser-extension/assets/41711440/a998f58e-8bea-4ec7-a00c-7ae5446a3d12"> </video>

**Comment by DanielSinclair** [comment]
@estebanmino Added to the merge queue after our testing FYII

**Pull request merged**
