### PR TITLE
degen issues

### PR DESCRIPTION
**Pull request by estebanmino**
Fixes BX-1427
Figma link (if any):

## What changed (plus any additional context for devs)

deatils in ticket

- degen not being active by default fixed here https://github.com/rainbow-me/browser-extension/commit/cfff9c5e2ec84ebbc01b16a391c5d2a604f303ee
- avoid rpc duplication fixed here https://github.com/rainbow-me/browser-extension/commit/f8ac1b7f7fd51246f1c6fa0d4150907df7a6452e we were just adding a new rpc without checking the old rpc is the same than the new one
- adding a migration to add degen rpc in case is missing https://github.com/rainbow-me/browser-extension/commit/17952ad3dd74d992fc62d7996c3c2a09344c2956

### CODE REVIEW

**Review by DanielSinclair — APPROVED** [review]
Didn't have a wallet in a broken state to test against, but migration succeeded for me and Degen Chain works as expected

**Comment by DanielSinclair** [comment]
cc @BrodyHughes do you have a broken dev wallet in any of these states that you can test?
Screenshot 2024-04-22 135325
Screenshot 2024-04-22 at 4 15 08 PM
Screenshot 2024-04-23 at 3 48 05 PM

**Review by greg-schrammel — APPROVED** [review]

**Comment by DanielSinclair** [comment]
@estebanmino Released this internally, and tested with the existing state of my internal build, and it looks like two instance of the chains are added, but the RPC list is empty. These screenshots are the same before and after the upgrade
Screenshot 2024-04-24 at 11 25 30 PM
Screenshot 2024-04-24 at 11 25 35 PM

**Comment by DanielSinclair** [comment]
Dumped local state to see if we can diagnose that way:

**`rainbow.zustand.customRPCs`**:
```json
{
    "state": {
        "customChains": {},
        "customRPCs": {}
    },
    "version": 0
}
```
**`rainbow.zustand.userChains`**:
```json
{
    "state": {
        "userChains": {
            "1": true,
            "10": true,
            "56": true,
            "137": true,
            "8453": true,
            "42161": true,
            "43114": true,
            "81457": true,
            "7777777": true,
            "666666666": true
        },
        "userChainsOrder": [1, 10, 56, 137, 8453, 42161, 43114, 81457, 7777777, 666666666]
    },
    "version": 4
}
```

**`rainbow.zustand.rainbowChains`**:
```json
"{\"state\":{\"rainbowChains\":{\"1\":{\"activeRpcUrl\":\"https://eth-mainnet.g.alchemy.com/v2/7A_gwNuV-oCQhMJnhlOdHaPo1yJZnp39\",\"chains\":[{\"id\":1,\"network\":\"homestead\",\"name\":\"Ethereum\",\"nativeCurrency\":{\"name\":\"Ether\",\"symbol\":\"ETH\",\"decimals\":18},\"rpcUrls\":{\"default\":{\"http\":[\"https://eth-mainnet.g.alchemy.com/v2/7A_gwNuV-oCQhMJnhlOdHaPo1yJZnp39\"]},\"public\":{\"http\":[\"https://eth-mainnet.g.alchemy.com/v2/7A_gwNuV-oCQhMJnhlOdHaPo1yJZnp39\"]}},\"blockExplorers\":{\"etherscan\":{\"name\":\"Etherscan\",\"url\":\"https://etherscan.io\"},\"default\":{\"name\":\"Etherscan\",\"url\":\"https://etherscan.io\"}},\"contracts\":{\"ensRegistry\":{\"address\":\"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e\"},\"ensUniversalResolver\":{\"address\":\"0xc0497E381f536Be9ce14B0dD3817cBcAe57d2F62\",\"blockCreated\":16966585},\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":14353601}}}]},\"10\":{\"activeRpcUrl\":\"https://opt-mainnet.g.alchemy.com/v2/kWJCWHTFOBMCbuVDgf_96uIuOkl1hSED\",\"chains\":[{\"id\":10,\"name\":\"Optimism\",\"network\":\"optimism\",\"nativeCurrency\":{\"name\":\"Ether\",\"symbol\":\"ETH\",\"decimals\":18},\"rpcUrls\":{\"default\":{\"http\":[\"https://opt-mainnet.g.alchemy.com/v2/kWJCWHTFOBMCbuVDgf_96uIuOkl1hSED\"]},\"public\":{\"http\":[\"https://opt-mainnet.g.alchemy.com/v2/kWJCWHTFOBMCbuVDgf_96uIuOkl1hSED\"]}},\"blockExplorers\":{\"etherscan\":{\"name\":\"Etherscan\",\"url\":\"https://optimistic.etherscan.io\"},\"default\":{\"name\":\"Optimism Explorer\",\"url\":\"https://explorer.optimism.io\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":4286263}},\"formatters\":{\"block\":{\"type\":\"block\"},\"transaction\":{\"type\":\"transaction\"},\"transactionReceipt\":{\"type\":\"transactionReceipt\"}}}]},\"25\":{\"chains\":[{\"id\":25,\"name\":\"Cronos Mainnet\",\"network\":\"Cronos Mainnet\",\"nativeCurrency\":{\"symbol\":\"CRO\",\"decimals\":18,\"name\":\"Cronos\"},\"rpcUrls\":{\"default\":{\"http\":[\"https://evm.cronos.org\"]},\"public\":{\"http\":[\"https://evm.cronos.org\"]}},\"testnet\":false}],\"activeRpcUrl\":\"https://evm.cronos.org\"},\"56\":{\"activeRpcUrl\":\"https://burned-solitary-breeze.bsc.quiknode.pro/6cc18aa3b4a535505853903e4a890ddccd2a9817\",\"chains\":[{\"id\":56,\"name\":\"BSC\",\"network\":\"bsc\",\"nativeCurrency\":{\"decimals\":18,\"name\":\"BNB\",\"symbol\":\"BNB\"},\"rpcUrls\":{\"default\":{\"http\":[\"https://burned-solitary-breeze.bsc.quiknode.pro/6cc18aa3b4a535505853903e4a890ddccd2a9817\"]},\"public\":{\"http\":[\"https://burned-solitary-breeze.bsc.quiknode.pro/6cc18aa3b4a535505853903e4a890ddccd2a9817\"]}},\"blockExplorers\":{\"etherscan\":{\"name\":\"BscScan\",\"url\":\"https://bscscan.com\"},\"default\":{\"name\":\"BscScan\",\"url\":\"https://bscscan.com\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":15921452}}}]},\"97\":{\"activeRpcUrl\":\"https://thrumming-shy-lake.bsc-testnet.quiknode.pro/7f21bf4972486182cbfaff80f8fb2eb5319740db/\",\"chains\":[{\"id\":97,\"name\":\"BSC Testnet\",\"network\":\"bsc-testnet\",\"nativeCurrency\":{\"decimals\":18,\"name\":\"BNB\",\"symbol\":\"tBNB\"},\"rpcUrls\":{\"default\":{\"http\":[\"https://thrumming-shy-lake.bsc-testnet.quiknode.pro/7f21bf4972486182cbfaff80f8fb2eb5319740db/\"]},\"public\":{\"http\":[\"https://thrumming-shy-lake.bsc-testnet.quiknode.pro/7f21bf4972486182cbfaff80f8fb2eb5319740db/\"]}},\"blockExplorers\":{\"etherscan\":{\"name\":\"BscScan\",\"url\":\"https://testnet.bscscan.com\"},\"default\":{\"name\":\"BscScan\",\"url\":\"https://testnet.bscscan.com\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":17422483}},\"testnet\":true}]},\"137\":{\"activeRpcUrl\":\"https://polygon-mainnet.g.alchemy.com/v2/1Njwt1jbGrjSvNTX1tED9LINcN7WkVO8\",\"chains\":[{\"id\":137,\"name\":\"Polygon\",\"network\":\"matic\",\"nativeCurrency\":{\"name\":\"MATIC\",\"symbol\":\"MATIC\",\"decimals\":18},\"rpcUrls\":{\"default\":{\"http\":[\"https://polygon-mainnet.g.alchemy.com/v2/1Njwt1jbGrjSvNTX1tED9LINcN7WkVO8\"]},\"public\":{\"http\":[\"https://polygon-mainnet.g.alchemy.com/v2/1Njwt1jbGrjSvNTX1tED9LINcN7WkVO8\"]}},\"blockExplorers\":{\"etherscan\":{\"name\":\"PolygonScan\",\"url\":\"https://polygonscan.com\"},\"default\":{\"name\":\"PolygonScan\",\"url\":\"https://polygonscan.com\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":25770160}}}]},\"8453\":{\"activeRpcUrl\":\"https://base-mainnet.g.alchemy.com/v2/_GoJW81Di-rhQtRa-ABzp_Aq5rh82StE\",\"chains\":[{\"id\":8453,\"network\":\"base\",\"name\":\"Base\",\"nativeCurrency\":{\"name\":\"Ether\",\"symbol\":\"ETH\",\"decimals\":18},\"rpcUrls\":{\"default\":{\"http\":[\"https://base-mainnet.g.alchemy.com/v2/_GoJW81Di-rhQtRa-ABzp_Aq5rh82StE\"]},\"public\":{\"http\":[\"https://base-mainnet.g.alchemy.com/v2/_GoJW81Di-rhQtRa-ABzp_Aq5rh82StE\"]}},\"blockExplorers\":{\"blockscout\":{\"name\":\"Basescout\",\"url\":\"https://base.blockscout.com\"},\"default\":{\"name\":\"Basescan\",\"url\":\"https://basescan.org\"},\"etherscan\":{\"name\":\"Basescan\",\"url\":\"https://basescan.org\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":5022}},\"formatters\":{\"block\":{\"type\":\"block\"},\"transaction\":{\"type\":\"transaction\"},\"transactionReceipt\":{\"type\":\"transactionReceipt\"}}}]},\"17000\":{\"activeRpcUrl\":\"https://bitter-prettiest-vineyard.ethereum-holesky.quiknode.pro/c9bcb2709d0341ae9ba13859bd4fc559ca6e83fd/\",\"chains\":[{\"id\":17000,\"network\":\"holesky\",\"name\":\"Holesky\",\"nativeCurrency\":{\"name\":\"Holesky Ether\",\"symbol\":\"ETH\",\"decimals\":18},\"rpcUrls\":{\"default\":{\"http\":[\"https://bitter-prettiest-vineyard.ethereum-holesky.quiknode.pro/c9bcb2709d0341ae9ba13859bd4fc559ca6e83fd/\"]},\"public\":{\"http\":[\"https://bitter-prettiest-vineyard.ethereum-holesky.quiknode.pro/c9bcb2709d0341ae9ba13859bd4fc559ca6e83fd/\"]}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":77}},\"testnet\":true}]},\"42161\":{\"activeRpcUrl\":\"https://arb-mainnet.g.alchemy.com/v2/YXc9Lkb3fErzP0O_c2sAZfi5iV-9aiZg\",\"chains\":[{\"id\":42161,\"name\":\"Arbitrum\",\"network\":\"arbitrum\",\"nativeCurrency\":{\"name\":\"Ether\",\"symbol\":\"ETH\",\"decimals\":18},\"rpcUrls\":{\"default\":{\"http\":[\"https://arb-mainnet.g.alchemy.com/v2/YXc9Lkb3fErzP0O_c2sAZfi5iV-9aiZg\"]},\"public\":{\"http\":[\"https://arb-mainnet.g.alchemy.com/v2/YXc9Lkb3fErzP0O_c2sAZfi5iV-9aiZg\"]}},\"blockExplorers\":{\"etherscan\":{\"name\":\"Arbiscan\",\"url\":\"https://arbiscan.io\"},\"default\":{\"name\":\"Arbiscan\",\"url\":\"https://arbiscan.io\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":7654707}}}]},\"43113\":{\"activeRpcUrl\":\"https://api.avax-test.network/\",\"chains\":[{\"id\":43113,\"name\":\"Avalanche Fuji\",\"network\":\"avalanche-fuji\",\"nativeCurrency\":{\"decimals\":18,\"name\":\"Avalanche Fuji\",\"symbol\":\"AVAX\"},\"rpcUrls\":{\"default\":{\"http\":[\"https://api.avax-test.network/\"]},\"public\":{\"http\":[\"https://api.avax-test.network/\"]}},\"blockExplorers\":{\"etherscan\":{\"name\":\"SnowTrace\",\"url\":\"https://testnet.snowtrace.io\"},\"default\":{\"name\":\"SnowTrace\",\"url\":\"https://testnet.snowtrace.io\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":7096959}},\"testnet\":true}]},\"43114\":{\"activeRpcUrl\":\"https://proportionate-crimson-owl.avalanche-mainnet.quiknode.pro/c2885b6042936e330db92920be4b413fccc8af4e/ext/bc/C/rpc/\",\"chains\":[{\"id\":43114,\"name\":\"Avalanche\",\"network\":\"avalanche\",\"nativeCurrency\":{\"decimals\":18,\"name\":\"Avalanche\",\"symbol\":\"AVAX\"},\"rpcUrls\":{\"default\":{\"http\":[\"https://proportionate-crimson-owl.avalanche-mainnet.quiknode.pro/c2885b6042936e330db92920be4b413fccc8af4e/ext/bc/C/rpc/\"]},\"public\":{\"http\":[\"https://proportionate-crimson-owl.avalanche-mainnet.quiknode.pro/c2885b6042936e330db92920be4b413fccc8af4e/ext/bc/C/rpc/\"]}},\"blockExplorers\":{\"etherscan\":{\"name\":\"SnowTrace\",\"url\":\"https://snowtrace.io\"},\"default\":{\"name\":\"SnowTrace\",\"url\":\"https://snowtrace.io\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":11907934}}}]},\"80001\":{\"activeRpcUrl\":\"https://polygon-mumbai.g.alchemy.com/v2/eDcIGd_8qMdv_yXJ7fROF9_nv9sAlt5k\",\"chains\":[{\"id\":80001,\"name\":\"Polygon Mumbai\",\"network\":\"maticmum\",\"nativeCurrency\":{\"name\":\"MATIC\",\"symbol\":\"MATIC\",\"decimals\":18},\"rpcUrls\":{\"default\":{\"http\":[\"https://polygon-mumbai.g.alchemy.com/v2/eDcIGd_8qMdv_yXJ7fROF9_nv9sAlt5k\"]},\"public\":{\"http\":[\"https://polygon-mumbai.g.alchemy.com/v2/eDcIGd_8qMdv_yXJ7fROF9_nv9sAlt5k\"]}},\"blockExplorers\":{\"etherscan\":{\"name\":\"PolygonScan\",\"url\":\"https://mumbai.polygonscan.com\"},\"default\":{\"name\":\"PolygonScan\",\"url\":\"https://mumbai.polygonscan.com\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":25770160}},\"testnet\":true}]},\"80002\":{\"activeRpcUrl\":\"https://rpc-amoy.polygon.technology\",\"chains\":[{\"id\":80002,\"name\":\"Polygon Amoy\",\"network\":\"polygon-amoy\",\"nativeCurrency\":{\"decimals\":18,\"name\":\"MATIC\",\"symbol\":\"MATIC\"},\"rpcUrls\":{\"default\":{\"http\":[\"https://rpc-amoy.polygon.technology\"]},\"public\":{\"http\":[\"https://rpc-amoy.polygon.technology\"]}},\"testnet\":true}]},\"81457\":{\"activeRpcUrl\":\"https://dry-green-pallet.blast-mainnet.quiknode.pro/8451d7d3501995d2d9826fa91a0c890d2b4fa669/\",\"chains\":[{\"id\":81457,\"name\":\"Blast\",\"network\":\"blast\",\"rpcUrls\":{\"default\":{\"http\":[\"https://dry-green-pallet.blast-mainnet.quiknode.pro/8451d7d3501995d2d9826fa91a0c890d2b4fa669/\"]},\"public\":{\"http\":[\"https://dry-green-pallet.blast-mainnet.quiknode.pro/8451d7d3501995d2d9826fa91a0c890d2b4fa669/\"]}},\"blockExplorers\":{\"default\":{\"name\":\"Blastscan\",\"url\":\"https://blastscan.io/\"}},\"nativeCurrency\":{\"name\":\"Blast\",\"symbol\":\"BLAST\",\"decimals\":18}}]},\"84532\":{\"activeRpcUrl\":\"https://base-sepolia.g.alchemy.com/v2/u_MUhnrI7QWHOJ3xgoX2qS72a6A7y-Yn\",\"chains\":[{\"id\":84532,\"network\":\"base-sepolia\",\"name\":\"Base Sepolia\",\"nativeCurrency\":{\"name\":\"Sepolia Ether\",\"symbol\":\"ETH\",\"decimals\":18},\"rpcUrls\":{\"default\":{\"http\":[\"https://base-sepolia.g.alchemy.com/v2/u_MUhnrI7QWHOJ3xgoX2qS72a6A7y-Yn\"]},\"public\":{\"http\":[\"https://base-sepolia.g.alchemy.com/v2/u_MUhnrI7QWHOJ3xgoX2qS72a6A7y-Yn\"]}},\"blockExplorers\":{\"blockscout\":{\"name\":\"Blockscout\",\"url\":\"https://base-sepolia.blockscout.com\"},\"default\":{\"name\":\"Blockscout\",\"url\":\"https://base-sepolia.blockscout.com\"}},\"testnet\":true,\"sourceId\":11155111,\"formatters\":{\"block\":{\"type\":\"block\"},\"transaction\":{\"type\":\"transaction\"},\"transactionReceipt\":{\"type\":\"transactionReceipt\"}}}]},\"421614\":{\"activeRpcUrl\":\"https://arb-sepolia.g.alchemy.com/v2/cVjXJXnGbajoCEorvbKzGOXqUCi6S6i5\",\"chains\":[{\"id\":421614,\"name\":\"Arbitrum Sepolia\",\"network\":\"arbitrum-sepolia\",\"nativeCurrency\":{\"name\":\"Arbitrum Sepolia Ether\",\"symbol\":\"ETH\",\"decimals\":18},\"rpcUrls\":{\"default\":{\"http\":[\"https://arb-sepolia.g.alchemy.com/v2/cVjXJXnGbajoCEorvbKzGOXqUCi6S6i5\"]},\"public\":{\"http\":[\"https://arb-sepolia.g.alchemy.com/v2/cVjXJXnGbajoCEorvbKzGOXqUCi6S6i5\"]}},\"blockExplorers\":{\"etherscan\":{\"name\":\"Arbiscan\",\"url\":\"https://sepolia.arbiscan.io\"},\"default\":{\"name\":\"Arbiscan\",\"url\":\"https://sepolia.arbiscan.io\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":81930}},\"testnet\":true}]},\"7777777\":{\"activeRpcUrl\":\"https://rpc.zora.energy\",\"chains\":[{\"id\":7777777,\"name\":\"Zora\",\"network\":\"zora\",\"nativeCurrency\":{\"decimals\":18,\"name\":\"Ether\",\"symbol\":\"ETH\"},\"rpcUrls\":{\"default\":{\"http\":[\"https://rpc.zora.energy\"]},\"public\":{\"http\":[\"https://rpc.zora.energy\"]}},\"blockExplorers\":{\"default\":{\"name\":\"Explorer\",\"url\":\"https://explorer.zora.energy\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xcA11bde05977b3631167028862bE2a173976CA11\",\"blockCreated\":5882}},\"formatters\":{\"block\":{\"type\":\"block\"},\"transaction\":{\"type\":\"transaction\"},\"transactionReceipt\":{\"type\":\"transactionReceipt\"}}}]},\"11155111\":{\"activeRpcUrl\":\"https://eth-sepolia.g.alchemy.com/v2/CqF9F0YkzSMqnMdXng05vQclab1g79ss\",\"chains\":[{\"id\":11155111,\"network\":\"sepolia\",\"name\":\"Sepolia\",\"nativeCurrency\":{\"name\":\"Sepolia Ether\",\"symbol\":\"SEP\",\"decimals\":18},\"rpcUrls\":{\"default\":{\"http\":[\"https://eth-sepolia.g.alchemy.com/v2/CqF9F0YkzSMqnMdXng05vQclab1g79ss\"]},\"public\":{\"http\":[\"https://eth-sepolia.g.alchemy.com/v2/CqF9F0YkzSMqnMdXng05vQclab1g79ss\"]}},\"blockExplorers\":{\"etherscan\":{\"name\":\"Etherscan\",\"url\":\"https://sepolia.etherscan.io\"},\"default\":{\"name\":\"Etherscan\",\"url\":\"https://sepolia.etherscan.io\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":6507670}},\"testnet\":true}]},\"11155420\":{\"activeRpcUrl\":\"https://opt-sepolia.g.alchemy.com/v2/Xr6jYGuSVEUGTmX5Zohm1xBz7PwdGrEk\",\"chains\":[{\"id\":11155420,\"name\":\"Optimism Sepolia\",\"network\":\"optimism-sepolia\",\"nativeCurrency\":{\"name\":\"Sepolia Ether\",\"symbol\":\"ETH\",\"decimals\":18},\"rpcUrls\":{\"default\":{\"http\":[\"https://opt-sepolia.g.alchemy.com/v2/Xr6jYGuSVEUGTmX5Zohm1xBz7PwdGrEk\"]},\"public\":{\"http\":[\"https://opt-sepolia.g.alchemy.com/v2/Xr6jYGuSVEUGTmX5Zohm1xBz7PwdGrEk\"]}},\"blockExplorers\":{\"blockscout\":{\"name\":\"Blockscout\",\"url\":\"https://optimism-sepolia.blockscout.com\"},\"default\":{\"name\":\"Blockscout\",\"url\":\"https://optimism-sepolia.blockscout.com\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xca11bde05977b3631167028862be2a173976ca11\",\"blockCreated\":1620204}},\"testnet\":true,\"formatters\":{\"block\":{\"type\":\"block\"},\"transaction\":{\"type\":\"transaction\"},\"transactionReceipt\":{\"type\":\"transactionReceipt\"}}}]},\"168587773\":{\"activeRpcUrl\":\"https://sepolia.blast.io\",\"chains\":[{\"id\":168587773,\"name\":\"Blast Sepolia\",\"network\":\"blast-sepolia\",\"nativeCurrency\":{\"decimals\":18,\"name\":\"Ether\",\"symbol\":\"ETH\"},\"rpcUrls\":{\"default\":{\"http\":[\"https://sepolia.blast.io\"]},\"public\":{\"http\":[\"https://sepolia.blast.io\"]}},\"testnet\":true}]},\"999999999\":{\"activeRpcUrl\":\"https://sepolia.rpc.zora.energy\",\"chains\":[{\"id\":999999999,\"name\":\"Zora Sepolia\",\"network\":\"zora-sepolia\",\"nativeCurrency\":{\"decimals\":18,\"name\":\"Zora Sepolia\",\"symbol\":\"ETH\"},\"rpcUrls\":{\"default\":{\"http\":[\"https://sepolia.rpc.zora.energy\"]},\"public\":{\"http\":[\"https://sepolia.rpc.zora.energy\"]}},\"blockExplorers\":{\"default\":{\"name\":\"Zora Sepolia Explorer\",\"url\":\"https://sepolia.explorer.zora.energy/\"}},\"contracts\":{\"multicall3\":{\"address\":\"0xcA11bde05977b3631167028862bE2a173976CA11\",\"blockCreated\":83160}},\"testnet\":true,\"formatters\":{\"block\":{\"type\":\"block\"},\"transaction\":{\"type\":\"transaction\"},\"transactionReceipt\":{\"type\":\"transactionReceipt\"}}}]}}},\"version\":7}"
```

**Pull request merged**
