### PR TITLE
feat(AcceptRequest): hardware wallet feedback

### PR DESCRIPTION
**Pull request by Schrammel**
Fixes BX-####

I did it because I spent a brief period watching the loading spinner until I remembered that I was using a hardware wallet.

## What changed (plus any additional context for devs)
If we're awaiting confirmation on the hardware wallet, this message will be displayed.

## Screen recordings / screenshots

https://github.com/rainbow-me/browser-extension/assets/5888609/c52c6c91-8cba-45c3-8db2-fd4677e6b143

## What to test

Test whether the message appears while awaiting confirmation on a hardware wallet during sign message or transaction submission

### CODE REVIEW

**Review by greg-schrammel — APPROVED** [review]
🙏🙏🙏

**Review by brunobar79 — APPROVED** [review]
Thanks!

**Comment by Schrammel** [comment]
I can't test it after performing a rebase, something is broken on importing/creating an account

**Comment by Schrammel** [comment]
i can't test it after performing a rebase, something is broken after import/create  an account

**Pull request merged**
