### PR TITLE
feat: remote token search

### PR DESCRIPTION
**Pull request by magiziz**
Fixes BX-1505
Figma link (if any):

**IMPORTANT!** Merge [this](https://github.com/rainbow-me/browser-extension/pull/1579) PR first, before merging this. Since there are some bugs that were fixed + there will be merge conflicts.

## What changed (plus any additional context for devs)

We now support remote token search for verified assets and unverified assets in Cmd+K and unverified assets in token details page.

## Screen recordings / screenshots

https://github.com/rainbow-me/browser-extension/assets/53529533/efd3113a-1172-466e-8d0c-4707cf38fcf6

### Cmd+K:

- Type at least  **three** characters to search for a token.
- None of the  **unowned** tokens should have a badge on the right.
- You should see a **loading bar** in the Cmd+K menu if tokens are being searched.
- Try searching for your **owned** asset (e.g., "Ethereum" if you have ETH) and make sure that:
  - **Owned** assets are ranked as priority 1.
  - **Verified** assets are ranked as priority 2.
  - **Unverified** assets are ranked as priority 3.
  - You can see which assets are **verified** and **unverified** by looking at:
    - name (make sure the name doesn't sound like a scam if it's a verified asset)
    - icon (verified assets will have an icon)

### Token details page:

- If you select an unverified asset in Cmd+K you should be redirected to token details page and see the token details.

### CODE REVIEW

**Comment by estebanmino** [comment]
@magiziz what do you mean by `should have a badge on the right`? none of my assets have that, even owned assets

following question, for mainnet assets there's no difference between owned and unowned assets, is that ok?

**Comment by magiziz** [comment]
> @magiziz what do you mean by should have a badge on the right? none of my assets have that, even owned assets

@estebanmino Ah yeah those are confusing. The badges i'm talking about are these:

image

If you have owned token they badges should appear, but search tokens (unowned) shoudn't have any badge.


> following question, for mainnet assets there's no difference between owned and unowned assets, is that ok?

I think mainnet assets can be owned and unowned depending on what you have. For example if i own ethereum on base that's an owned asset, but if i search for ethereum on optimism and don't have that in my wallet we can consider it as unowned asset, but happy to do any changes. Lmk what you think.

**Review by estebanmino — APPROVED** [review]
lgtm!

**Review by BrodyHughes — APPROVED** [review]
tested all requested flows, lgtm.

**Pull request merged**
