### PR TITLE
scam dapp connection warning

### PR DESCRIPTION
**Pull request by greg-schrammel**
Fixes BX-####
Figma link (if any): https://www.figma.com/file/a33TH3fYEWNC6xTePxZ8sN/BX-Signing?type=design&node-id=251%3A21601&mode=design

## What changed (plus any additional context for devs)

Connect: Verified / Scam / Unverified (yet)

Screenshot 2023-10-11 at 17 33 11

Screenshot 2023-10-12 at 13 18 57

Screenshot 2023-10-11 at 17 33 58

Send tx: Verified / Scam / Unverified 

Screenshot 2023-10-16 at 20 26 16

Screenshot 2023-10-16 at 20 26 02

Screenshot 2023-10-16 at 20 26 31

Sign

Screenshot 2023-10-16 at 23 21 39

### CODE REVIEW

**Review by estebanmino — COMMENTED** [review]
code lgtm but i see some misalignments

image

the action buttons and the buttons section for the scam example in the middle is lower than the normal connect screen, seems like it should probably moved up to match the connect screen heights

**Comment by brunobar79** [comment]
Got a ton of conflicts to resolve. Ping me once those are fixed and I'll review it right away.

**Review by estebanmino — APPROVED** [review]
👨‍🍳

**Review by brunobar79 — APPROVED** [review]
🤝

**Pull request merged**
