### PR TITLE
hidden assets for magic menu (CmdK)

### PR DESCRIPTION
**Pull request by magiziz**
Fixes BX-1377
Figma link (if any):

## What changed (plus any additional context for devs)

- Added hide/unhide action for tokens and nfts in CmdK magic menu.
- Added "Hidden" label to hidden tokens and nfts. Similar to "Watching" label for watched wallets.
- Searching "hidden" in CmdK menu will show hidden assets.

## Screen recordings / screenshots

https://github.com/user-attachments/assets/a3b0e595-b268-4349-9f85-7db3b7050281

## What to test

Make sure hide and unhide actions work with tokens and nfts in CmdK menu.

### CODE REVIEW

**Comment by derHowie** [comment]
Hide/unhide functionality works, but if you pull up the cmd-k menu while you're on the assets list then return after hiding a token, the list's rendering seems to be messed up when you scroll. Sometimes there are blank gaps and sometimes there are overlaps. I'm guessing this means the keys are getting messed up or the new list needs a `.measure()` call after you hide/unhide something.

**Comment by DanielSinclair** [comment]
@magiziz Can you have a look at the issue Chris mentioned? Can get this merged this week

**Comment by estebanmino** [comment]
@derHowie is this ready for review?

**Comment by derHowie** [comment]
> @derHowie is this ready for review?

yes

**Review by estebanmino — APPROVED** [review]
code lgtm and fix is working locally

**Review by BrodyHughes — COMMENTED** [review]
LGTM but seeing one very small issue when you hide then un-hide L2 tokens I am seeing a gap in the token list that persists until you scroll.

<video src="https://github.com/user-attachments/assets/387cef6d-fe73-4658-adfd-68cdb255825a"></video>

**Review by brunobar79 — CHANGES_REQUESTED** [review]
See Brody's comment above

**Review by derHowie — APPROVED** [review]

**Comment by DanielSinclair** [comment]
Merging per Chris's recommendation about the token cell update issue. Created a follow-up ticket for that

**Pull request merged**
