### PR TITLE
chore: upgrade tokenSearchHttp version

### PR DESCRIPTION
**Pull request by derHowie**
Fixes BX-1594

## What changed (plus any additional context for devs)
I replaced our token search endpoint with the new one

## Screen recordings / screenshots
Screenshot 2024-08-19 at 12 28 37 PM

## What to test
There should not be any behavior changes in the API. We just need to ensure search functionality still works, although the token order may have changed for some lists.

### CODE REVIEW

**Review by BrodyHughes — APPROVED** [review]
lgtm!

**Review by DanielSinclair — APPROVED** [review]
Not seeing any issues!

**Comment by DanielSinclair** [comment]
@derHowie The "should be able to favorite a token and check the info button is present" e2e test oddly seems to be failing; not sure why

**Comment by DanielSinclair** [comment]
@derHowie Seeing the same failure; the CI screenshot doesn't show any assets but looks like the output modal is still presenting. Is there maybe a new network hang that causes a timing failure?
should_be_able_to_favorite_a_token_and_check_the_info_button_is_present_failure_1_2_3_4

**Pull request merged**
