### PR TITLE
Points weekly overview

### PR DESCRIPTION
**Pull request by greg-schrammel**
Fixes BX-1277
Figma link (if any):

## Screen recordings / screenshots

https://github.com/rainbow-me/browser-extension/assets/6232729/d20cafe8-2ca9-4bbb-a45f-8f02fdeac296

### CODE REVIEW

**Review by DanielSinclair — CHANGES_REQUESTED** [review]
Got stuck in a crash-loop after visiting the Points tab; not sure if I had an unenrolled or enrolled to points wallet active at that time
Screenshot 2024-01-25 at 12 51 05 AM

**Comment by estebanmino** [comment]
padding doesn't look right
image

left: figma
right: extension

**Review by DanielSinclair — APPROVED** [review]

**Comment by DanielSinclair** [comment]
@estebanmino pushed up a tweak to fix that header separator issue

**Review by BrodyHughes — CHANGES_REQUESTED** [review]
seeing similar behavior to what Daniel mentioned above.

**worked fine on:** rainbowtester.eth
**crashed on:** iamshrek.eth (had to re-sign up for points)
**crashed on:** vlt.brdy.eth (is a ledger)

<video src="https://github.com/rainbow-me/browser-extension/assets/41711440/84243004-d434-4a53-b24a-ffb75aadfe72">

**Review by BrodyHughes — APPROVED** [review]
crashes seem fixed

**Comment by DanielSinclair** [comment]
@greg-schrammel Added some crash fixes/tweaks based on QA. Please double check when you have a chance; merging and releasing now.

**Pull request merged**
