### PR TITLE
Fix network change popup in prod

### PR DESCRIPTION
**Pull request by brunobar79**
Fixes BX-1109
Figma link (if any):

## What changed (plus any additional context for devs)
We had to replace the hardcoded occurrences of `popup.css` after the webpack build is done and use the name given by webpack instead.

## Screen recordings / screenshots

PoW: https://recordit.co/7V1DKVVwBO

## What to test

Network change popup with dev mode disabled

### CODE REVIEW

**Review by estebanmino — COMMENTED** [review]
i still don't see it when running the extension with `yarn build`

https://www.loom.com/share/ad37c823184d4a138fad0aa3848c1471

**Comment by brunobar79** [comment]
> i still don't see it when running the extension with `yarn build`
> 
> https://www.loom.com/share/ad37c823184d4a138fad0aa3848c1471

I made a last minute change and that broke it. It's fixed now. Sorry about that @estebanmino !

**Review by estebanmino — APPROVED** [review]
🚀 🚀 🚀 🚀

**Review by derHowie — APPROVED** [review]
🤖

**Pull request merged**
