### PR TITLE
fix language name typo

### PR DESCRIPTION
**Pull request by defijesus**
fixes pt-br language name

### CODE REVIEW

**Comment by defijesus** [comment]
bom dia

**Comment by DanielSinclair** [comment]
@defijesus Thanks! If you're interested in helping to point out any differences or proof-reading, we can add European Portuguese as well.

**Review by DanielSinclair — APPROVED** [review]

**Comment by defijesus** [comment]
> @defijesus Thanks! If you're interested in helping to point out any differences or proof-reading, we can add European Portuguese as well.

Would love to contribute. After a quick look around I didn’t find the strings file. If you could point me to it, I’ll get to it

**Comment by defijesus** [comment]
Hey, “brasileiro” should be lowercase. “Português” is to refer people from Portugal, “português” is to refer language.

**Review by greg-schrammel — APPROVED** [review]

**Comment by DanielSinclair** [comment]
Cherry-picked the commit over to #1052 to resolve the merge issue

**Pull request closed without merging**
